### ISSUE TITLE
The Stadium Demo Crashes with an Out of Memory

### ISSUE THREAD

**Issue by cdiggins** [vimaec/vim-webgl-viewer#111]
@vim-sroberge / @jpenning12 : I tried the Stadium model recently (it used to work). And it now crashes regularly with an "out of memory" bug: 

https://vimaec.github.io/vim-webgl-viewer/?model=https%3A%2F%2Fvim.azureedge.net%2Fsamples%2Fstadium.vim

Can you try it briefly on your machines and let me know if it works? If not do you have any ideas what might be the culprit?

**Comment by jpenning12** [comment]
I am able to run it from my laptop in firefox



[cid:VIM-logo-sm_email_sig_dc880150-3b83-4396-999a-1db7e6af2264.png]<http://www.vimaec.com/>

Joel Pennington | Head of Product
+1 415.450.8735<tel:>
***@***.***


From: Christopher Diggins ***@***.***>
Sent: Monday, November 29, 2021 9:40 AM
To: vimaec/vim-webgl-viewer ***@***.***>
Cc: Joel Pennington ***@***.***>; Mention ***@***.***>
Subject: [vimaec/vim-webgl-viewer] The Stadium Demo Crashes with an Out of Memory (Issue #111)

[EXTERNAL EMAIL] DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

@vim-sroberge<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvim-sroberge&data=04%7C01%7Cjoel.pennington%40vimaec.com%7Cdecd09724a194760ec2008d9b35f38b5%7C4e8565867c874498956eab21660251e1%7C0%7C0%7C637738043841687120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VS44VfMtQXGhBEs6O8WtJsnJZ%2BKLjXVVy8oAOE1cEyU%3D&reserved=0> / @jpenning12<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpenning12&data=04%7C01%7Cjoel.pennington%40vimaec.com%7Cdecd09724a194760ec2008d9b35f38b5%7C4e8565867c874498956eab21660251e1%7C0%7C0%7C637738043841697077%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CNwqkJqlPXWIAVWI9R4EmiSNT5oARtpwlt%2B7ka2zxzk%3D&reserved=0> : I tried the Stadium model recently (it used to work). And it now crashes regularly with an "out of memory" bug:

https://vimaec.github.io/vim-webgl-viewer/?model=https%3A%2F%2Fvim.azureedge.net%2Fsamples%2Fstadium.vim<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvimaec.github.io%2Fvim-webgl-viewer%2F%3Fmodel%3Dhttps%253A%252F%252Fvim.azureedge.net%252Fsamples%252Fstadium.vim&data=04%7C01%7Cjoel.pennington%40vimaec.com%7Cdecd09724a194760ec2008d9b35f38b5%7C4e8565867c874498956eab21660251e1%7C0%7C0%7C637738043841707025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=68phXNsILV%2Bj01HraNu%2FYUITBuV2lpm3131L6Hg9WGo%3D&reserved=0>

Can you try it briefly on your machines and let me know if it works? If not do you have any ideas what might be the culprit?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvimaec%2Fvim-webgl-viewer%2Fissues%2F111&data=04%7C01%7Cjoel.pennington%40vimaec.com%7Cdecd09724a194760ec2008d9b35f38b5%7C4e8565867c874498956eab21660251e1%7C0%7C0%7C637738043841707025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VEGXFD5FS09crwf1U%2Bz2GXRhhPehUjgm45sZMMcVZtA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALLWK6MOVEZFF3AVBOU76B3UOO3FXANCNFSM5I7WUL5A&data=04%7C01%7Cjoel.pennington%40vimaec.com%7Cdecd09724a194760ec2008d9b35f38b5%7C4e8565867c874498956eab21660251e1%7C0%7C0%7C637738043841716989%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c21ZIseM51%2FaeypwwqoWAQaAUiUOvwMCPGko0VKQ3EE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjoel.pennington%40vimaec.com%7Cdecd09724a194760ec2008d9b35f38b5%7C4e8565867c874498956eab21660251e1%7C0%7C0%7C637738043841716989%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fDcqmVz9iTjREOP2efC580YyVMx%2B%2BrXfcX5U0T26v6E%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjoel.pennington%40vimaec.com%7Cdecd09724a194760ec2008d9b35f38b5%7C4e8565867c874498956eab21660251e1%7C0%7C0%7C637738043841726946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zLsmFbZPuTjg6sw5snDPOFLsrUT9dZLutXa4O1CSeA0%3D&reserved=0>.
