### ISSUE TITLE
Use a modern JavaScript bundler

### ISSUE THREAD

**Issue by cdiggins** [vimaec/vim-webgl-viewer#8]
We should probably upgrade to a modern bundler system instead of our hand-rolled concatenation script. 

Some options include:

- Rollup https://rollupjs.org/guide/en/
- WebPack https://webpack.js.org/

@Fuzzyma do you have a recommendation?

**Comment by cdiggins** [comment]
It should be noted that it is possible that no bundler works well with Three.JS today (https://discourse.threejs.org/t/three-js-file-size-when-importing-via-npm-and-bundling-with-webpack/8904/4) and (https://discourse.threejs.org/t/how-to-reduce-bundle-size-with-webpack/14607)

**Comment by Fuzzyma** [comment]
Rollup is probably the one you wanna go with. It's especially well suited for library authors.

My favorite is vite. It supports typescript by default and takes the dev experience to a new level. For bundling it also uses Rollup under the hood

**Comment by cdiggins** [comment]
Thank you very much for your suggestion. Do you think this is something we need to do sooner than later, or should we still wait a bit, and sort out the API first? It's been a couple of years since I investigated this problem, and sounds to me like Three.JS is still a bit of a mess (https://discourse.threejs.org/t/how-to-reduce-bundle-size-with-webpack/14607/11). I'm concerned about the overhead of learning a new bundler, pushing up build times, and having a potentially larger bundle than before. I would assume we need to get to a new version of Three.JS first, and then start using ESM modules.

**Comment by Fuzzyma** [comment]
You don't really have to care what threejs is doing. After all, it's just a dependency. Bundling is also nothing you do on every commit. It's only when you finally publish/release your code. A lot of people won't even care about the bundle and will use the source files directly anyway.

For this project, I would merge all the open PRs and move to esm as soon as possible because it actually speeds up development.
You also might want to start using eslint to enforce a code style
